### PR TITLE
Corrected the selection of a pane/page added to a notebook

### PR DESCRIPTION
**Pull request by Kinaou**
Here is my proposal of modification of the method `wxAuiManager::SetActivePane` for managing correctly the activated status of the notebook tabs.
I also defined the return value to the index of the activated pane in the panes list instead of returning _zero_ arbitrarily. It will avoid to call `GetActivePane` just after when needed.

This answers to the issue https://github.com/nhold/wxWidgets/issues/76

### CODE REVIEW

**Comment by nhold** [comment]
I am not confident I can sufficiently review this, @mjmacleod are you able to look at this?

**Comment by mjmacleod** [comment]
Okay, I'll try have a look in next few days.

**Comment by mjmacleod** [comment]
I'm not sure I 100% like this one, I'm a bit concerned it may have unintended consequences and I'm not in a position to test all possible scenarios right now.
I've put an alternative patch at the bottom of https://github.com/nhold/wxWidgets/issues/76 which I think we should consider instead, @Kinaou can you perhaps verify if the alternative patch works for you and/or if you are okay with it?

**Comment by mjmacleod** [comment]
Can we close this one?

**Comment by Kinaou** [comment]
I verified your patch, it is much simpler and works well for me. I've no objection to replace mine :)

**Comment by mjmacleod** [comment]
Okay great, thanks!

**Comment by Kinaou** [comment]
Just something I had done in my patch was to set a useful return value to the SetActivePane() method.

**Comment by mjmacleod** [comment]
Okay, happy for that to change.
It isn't going to cause any weird backwards incompatibilities is it? Can't see any reason why myself but just making sure :)

**Pull request closed without merging**
