### PR TITLE
Use a style flag to enable dynamic notebooks #56 and fix for issue #55

### PR DESCRIPTION
**Pull request by ghost**
I've also made some code cleanup to remove dead code.

### CODE REVIEW

**Comment by mjmacleod** [comment]
A few things:
1) The #if 0 blocks are in master as well - I think they should be left, at least for now.
2) Are you 100% sure it is safe to strip the flags only inside wxAuiNotebook::Init and not wxAuiNotebook::Create as well - I am a bit concerned that passing the flags unstripped to wxControl::Create may have unexpected consequences (thats why I added it in both places to be sure) 
3) I'm not 100% sure I follow the logic for the removal of IsNotebookPane - does it fix some bug? Is the problem that the IsNotebookPane logic doesn't take the new events into account?
I'm a bit concerned that there may be cases where the new logic is not identical and may cause problems, as it complicates the hiding/showing of windows somewhat, but will have to look closer.

**Comment by mjmacleod** [comment]
Okay, I see the reason for number 3 - sorry missed the comment on that before. So ignore number 3.

**Comment by ghost** [comment]
Hello Malcom,

1) I honestly don't like dead code, especially in a really long and complicated piece of code like this one. It makes things even more difficult to read, and in my experience those lines tends to stay forever, no one knowing why they are there and daring to remove them ...

2) I think it's not a problem for those flags, but it's true I don't know if it's the case on all platforms. If we set them on both locations, we should place their generation in a separate method to avoid code duplication. I've done that because I missed this duplication at my first try with funny side effects ...

**Comment by mjmacleod** [comment]
1) Agreed I'm not a huge fan either - but vadz was already complaining in the past about unnecessary changes so trying to keep the noise down here, as I would really just like to see this merged now -  I'd prefer we just leave the code in for now and then we can sort stuff like this out post-merge. There is I think a lot of other scope for clean up as well...

2) I also think it is not a problem - but I don't know for sure - I think lets just make a helper method and call it from both places to be sure, rather than risk some breakages in odd situations.

**Pull request merged**
