### PR TITLE
Avoid crash when moving 'static' auinotebook tab to 'dynamic' pane

### PR DESCRIPTION
**Pull request by Kinaou**
After having integrated the aui-dynamic-notebook branch in my own project, I am fallen in unsuspected cases. Especially I tried to move a tab from a wxAuiNotebook created manually to a 'dynamic' pane, the managed window of the tab being destroyed during the D&D. This operation is obviously not supported.
The commit '2c3290f' avoids at least the crash.

### CODE REVIEW

**Comment by mjmacleod** [comment]
Do you have 
wxAUI_NB_TAB_EXTERNAL_MOVE set on the notebook and wxAUI_MGR_ALLOW_EXTERNAL_MOVE on the target manager? This is meant to work if those are set though its possible its been broken at some point so would be good to know.
(Obviously the crash must still be fixed either way)

**Comment by Kinaou** [comment]
wxAUI_NB_TAB_EXTERNAL_MOVE is set on the notebook but indeed the wxAUI_MGR_ALLOW_EXTERNAL_MOVE is not set on the manager...

**Comment by nhold** [comment]
Is there anyway this pull request can be cleaned up a bit?

**Comment by Kinaou** [comment]
I would have liked, but I was unable to find how. I thought that may be at the time of acceptance you could choose what you want to apply.
But I would be grateful if you can tell me how to pull a request for a specific range of commits.

**Comment by Kinaou** [comment]
I'm reading about Git and GitHub. I will send a better Pull Request soon :)

**Pull request closed without merging**
