### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by ghost**
This is the documentation update needed for reintegration in the 3.1 branch of wxWidgets. Nathan and Malcom, can you proof read what I wrote ?

Regards
Laurent

### CODE REVIEW

**Comment by mjmacleod** [comment]
Hi Laurent,

Thanks again for this and sorry for the silence from my side, really buried in work here. Will try set aside some time for this in the next few days if at all possible!
- Malcolm

**Comment by vadz** [comment]
Laurent, thanks a lot for working on this!

My only remaining question is whether there are any incompatible changes? I thought there are/would be some, and if this is the case, they should be documented.

Thanks again!

**Comment by mjmacleod** [comment]
Had a brief scan through and other than what vadz has already noted looks great.
One extremely minor niggle - the comments for left and right notebook tabs should maybe mention that the tabs are still vertically orientated, as otherwise people who are expecting otherwise may be let down.

I'll try download the latest and give it a quick run through over the weekend if I can.

**Comment by ghost** [comment]
Vadim,
What is the best place in the documentation to list incompatibilities, and known bugs ?

**Comment by vadz** [comment]
I guess at the end of the AUI overview if there are not too many of them. If it's worth it, we could also create a separate page about the changes between 3.0 and 3.2 (as we did for 3.0 with `docs/doxygen/overviews/changes_since28.h`) and document them in a section there.

**Comment by ghost** [comment]
Ok, I've made the suggested changes. I hope I didn't forgot anything.

**Comment by nhold** [comment]
Hey I had a quick look and it looks like it's missing the incompatibilities with:

'wxAuiTabCtrl' has no member named 'DoShowHide'
'wxAuiTabCtrl' has no member named 'IsDragging'
'class wxAuiPaneInfo' has no member named 'IsDestroyOnClose'

I mean, I can add these methods in to shut the errors up for people using them and the first two are an easy fix the third will require a bit more.

**Comment by nhold** [comment]
Accidentally closed it, sorry.

**Pull request merged**
